PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS subjects (subject_id TEXT PRIMARY KEY, display_name TEXT NOT NULL, handle TEXT NOT NULL, avatar_seed TEXT NOT NULL, content_lang TEXT NOT NULL, domain_style TEXT NOT NULL, format_weights_json TEXT NOT NULL, enabled INTEGER NOT NULL DEFAULT 1, created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS materials (material_id TEXT PRIMARY KEY, subject_id TEXT NOT NULL, filename TEXT NOT NULL, file_uri TEXT NOT NULL, mime_type TEXT NOT NULL, page_count INTEGER, page_start INTEGER, page_end INTEGER, status TEXT NOT NULL, error_message TEXT, added_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS materials_subject_idx ON materials(subject_id);
CREATE TABLE IF NOT EXISTS atoms (atom_id TEXT PRIMARY KEY, subject_id TEXT NOT NULL, material_id TEXT NOT NULL, topic_label TEXT NOT NULL, kind TEXT NOT NULL, difficulty REAL NOT NULL, core TEXT NOT NULL, note TEXT, source_anchor TEXT NOT NULL, enabled INTEGER NOT NULL DEFAULT 1, created_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS atoms_subject_idx ON atoms(subject_id); CREATE INDEX IF NOT EXISTS atoms_material_idx ON atoms(material_id);
CREATE TABLE IF NOT EXISTS posts (id TEXT PRIMARY KEY, subject_id TEXT NOT NULL, atom_id TEXT NOT NULL, topic_key TEXT NOT NULL, format TEXT NOT NULL, persona_id TEXT NOT NULL, text TEXT NOT NULL, quiz_json TEXT, difficulty_b REAL NOT NULL, status TEXT NOT NULL DEFAULT 'unread', is_rare_card INTEGER NOT NULL DEFAULT 0, created_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS posts_status_idx ON posts(status); CREATE INDEX IF NOT EXISTS posts_atom_idx ON posts(atom_id); CREATE INDEX IF NOT EXISTS posts_arm_idx ON posts(topic_key,format);
CREATE TABLE IF NOT EXISTS interactions (id TEXT PRIMARY KEY, post_id TEXT NOT NULL, action TEXT NOT NULL, dwell_ms INTEGER, created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS bandit_arms (topic_key TEXT NOT NULL, format TEXT NOT NULL, alpha REAL NOT NULL DEFAULT 1, beta REAL NOT NULL DEFAULT 1, PRIMARY KEY(topic_key,format));
CREATE TABLE IF NOT EXISTS atom_memory (atom_id TEXT PRIMARY KEY, stability_days REAL NOT NULL DEFAULT 1, last_reviewed_at INTEGER, review_count INTEGER NOT NULL DEFAULT 0, lapse_count INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS user_topic_state (topic_key TEXT PRIMARY KEY, theta REAL NOT NULL DEFAULT 0, attempts INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS streak_state (id INTEGER PRIMARY KEY CHECK(id=1), current_streak INTEGER NOT NULL DEFAULT 0, longest_streak INTEGER NOT NULL DEFAULT 0, last_active_date TEXT, freezes_owned INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS xp_events (id TEXT PRIMARY KEY, amount INTEGER NOT NULL, reason TEXT NOT NULL, created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS deepdives (post_id TEXT PRIMARY KEY, thread_json TEXT NOT NULL, created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS usage_log (id TEXT PRIMARY KEY, created_at INTEGER NOT NULL, provider_id TEXT NOT NULL, model_id TEXT NOT NULL, purpose TEXT NOT NULL, input_tokens INTEGER NOT NULL, output_tokens INTEGER NOT NULL, est_cost_usd REAL NOT NULL);
CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value_json TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS generation_runtime (id INTEGER PRIMARY KEY CHECK(id=1), lease_token TEXT, lease_expires_at INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS extraction_jobs (job_id TEXT PRIMARY KEY, subject_id TEXT NOT NULL UNIQUE REFERENCES subjects(subject_id) ON DELETE CASCADE, status TEXT NOT NULL, trigger TEXT NOT NULL, completed_units INTEGER NOT NULL DEFAULT 0, total_units INTEGER NOT NULL DEFAULT 0, progress_label TEXT, attempt_count INTEGER NOT NULL DEFAULT 0, next_attempt_at INTEGER, last_error_code TEXT, last_error TEXT, lease_token TEXT, lease_expires_at INTEGER NOT NULL DEFAULT 0, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, finished_at INTEGER);
CREATE INDEX IF NOT EXISTS extraction_jobs_runnable_idx ON extraction_jobs(status,next_attempt_at,lease_expires_at,created_at);
INSERT OR IGNORE INTO streak_state(id) VALUES(1);
INSERT OR IGNORE INTO generation_runtime(id) VALUES(1);
